import type { SupportedLocale } from '@/hooks/useCurrentLocale'

type NavTextMap = {
  sections: Record<string, string>
  quickShare: string
  quickMaps: string
  pinnedActionLabel: string
  itemByHref: Record<string, { label?: string; description?: string }>
}

export const navLocaleText: Record<SupportedLocale, NavTextMap> = {
  tr: {
    sections: {
      Paylasim: 'Paylasim',
      Haritalar: 'Haritalar',
      Kesif: 'Kesif',
      Ticaret: 'Ticaret',
      Hesap: 'Hesap',
    },
    quickShare: 'Hizli Paylasim',
    quickMaps: 'Hizli Haritalar',
    pinnedActionLabel: 'Spot Olustur',
    itemByHref: {},
  },
  en: {
    sections: {
      Paylasim: 'Share',
      Haritalar: 'Maps',
      Kesif: 'Discover',
      Ticaret: 'Commerce',
      Hesap: 'Account',
    },
    quickShare: 'Quick Share',
    quickMaps: 'Quick Maps',
    pinnedActionLabel: 'Create Spot',
    itemByHref: {
      '/create-spot': { label: 'Create Spot', description: 'Open a request and get community help' },
      '/share/rare': { label: 'I Spotted Rare', description: 'Share a rare item sighting quickly' },
      '/discovery?compose=1': { label: 'Rare Travel', description: 'Share visuals and stories with community' },
      '/share/collection': { label: 'Add Collection', description: 'Publish your physical collection item' },
      '/rare-map': { label: 'Rare Item Map', description: 'Physical rare item sightings' },
      '/rare-travel-map': { label: 'Rare Travel Map', description: 'Discovery social shares' },
      '/rare-travel-plan': { label: 'Rare Travel Plan', description: 'Route-based smart rare planner' },
      '/': { label: 'Home' },
      '/sightings': { label: 'Helps' },
      '/virtual-sightings': { label: 'Virtual Helps' },
      '/discovery': { label: 'Rare Travel' },
      '/seyahat-rotalari': { label: 'Rare Routes', description: 'Route posts generated from live travel' },
      '/museum': { label: 'Museum' },
      '/collection': { label: 'Collection' },
      '/spots': { label: 'Spots' },
      '/for-business': { label: 'Businesses' },
      '/products': { label: 'Products' },
      '/messages': { label: 'Messages' },
    },
  },
  de: {
    sections: {
      Paylasim: 'Teilen',
      Haritalar: 'Karten',
      Kesif: 'Entdecken',
      Ticaret: 'Handel',
      Hesap: 'Konto',
    },
    quickShare: 'Schnell Teilen',
    quickMaps: 'Schnelle Karten',
    pinnedActionLabel: 'Spot erstellen',
    itemByHref: {
      '/create-spot': { label: 'Spot erstellen', description: 'Anfrage stellen und Community-Hilfe erhalten' },
      '/share/rare': { label: 'Selten gesehen', description: 'Seltene Artikel-Sichtung schnell melden' },
      '/discovery?compose=1': { label: 'Seltene Reise', description: 'Bilder und Geschichten mit der Community teilen' },
      '/share/collection': { label: 'Sammlung hinzufugen', description: 'Physisches Sammlungsstueck veroffentlichen' },
      '/rare-map': { label: 'Karte seltener Artikel', description: 'Physische Sichtungen seltener Artikel' },
      '/rare-travel-map': { label: 'Seltene Reisekarte', description: 'Discovery soziale Beitrage' },
      '/rare-travel-plan': { label: 'Seltener Reiseplan', description: 'Routenbasierter intelligenter Planer' },
      '/': { label: 'Startseite' },
      '/sightings': { label: 'Hilfen' },
      '/virtual-sightings': { label: 'Virtuelle Hilfen' },
      '/discovery': { label: 'Seltene Reise' },
      '/seyahat-rotalari': { label: 'Seltene Routen', description: 'Routenbeitrage aus Live-Reisen' },
      '/museum': { label: 'Museum' },
      '/collection': { label: 'Sammlung' },
      '/spots': { label: 'Spots' },
      '/for-business': { label: 'Unternehmen' },
      '/products': { label: 'Produkte' },
      '/messages': { label: 'Nachrichten' },
    },
  },
  fr: {
    sections: {
      Paylasim: 'Partager',
      Haritalar: 'Cartes',
      Kesif: 'Decouvrir',
      Ticaret: 'Commerce',
      Hesap: 'Compte',
    },
    quickShare: 'Partage Rapide',
    quickMaps: 'Cartes Rapides',
    pinnedActionLabel: 'Creer un spot',
    itemByHref: {
      '/create-spot': { label: 'Creer un spot', description: 'Ouvrir une demande et obtenir l aide de la communaute' },
      '/share/rare': { label: 'Rare observe', description: 'Signalez rapidement un objet rare apercu' },
      '/discovery?compose=1': { label: 'Voyage rare', description: 'Partager visuels et histoires avec la communaute' },
      '/share/collection': { label: 'Ajouter collection', description: 'Publiez votre piece de collection physique' },
      '/rare-map': { label: 'Carte objets rares', description: 'Observations physiques d objets rares' },
      '/rare-travel-map': { label: 'Carte voyage rare', description: 'Partages sociaux Discovery' },
      '/rare-travel-plan': { label: 'Plan voyage rare', description: 'Planificateur intelligent base sur les itineraires' },
      '/': { label: 'Accueil' },
      '/sightings': { label: 'Aides' },
      '/virtual-sightings': { label: 'Aides virtuelles' },
      '/discovery': { label: 'Voyage rare' },
      '/seyahat-rotalari': { label: 'Itineraires rares', description: 'Publications d itineraires issus de voyages en direct' },
      '/museum': { label: 'Musee' },
      '/collection': { label: 'Collection' },
      '/spots': { label: 'Spots' },
      '/for-business': { label: 'Entreprises' },
      '/products': { label: 'Produits' },
      '/messages': { label: 'Messages' },
    },
  },
  es: {
    sections: {
      Paylasim: 'Compartir',
      Haritalar: 'Mapas',
      Kesif: 'Descubrir',
      Ticaret: 'Comercio',
      Hesap: 'Cuenta',
    },
    quickShare: 'Compartir Rapido',
    quickMaps: 'Mapas Rapidos',
    pinnedActionLabel: 'Crear spot',
    itemByHref: {
      '/create-spot': { label: 'Crear spot', description: 'Abre una solicitud y recibe ayuda de la comunidad' },
      '/share/rare': { label: 'Vi algo raro', description: 'Comparte rapidamente un avistamiento raro' },
      '/discovery?compose=1': { label: 'Viaje raro', description: 'Comparte imagenes e historias con la comunidad' },
      '/share/collection': { label: 'Agregar coleccion', description: 'Publica tu pieza de coleccion fisica' },
      '/rare-map': { label: 'Mapa objetos raros', description: 'Avistamientos fisicos de objetos raros' },
      '/rare-travel-map': { label: 'Mapa viaje raro', description: 'Publicaciones sociales de Discovery' },
      '/rare-travel-plan': { label: 'Plan viaje raro', description: 'Planificador inteligente basado en rutas' },
      '/': { label: 'Inicio' },
      '/sightings': { label: 'Ayudas' },
      '/virtual-sightings': { label: 'Ayudas virtuales' },
      '/discovery': { label: 'Viaje raro' },
      '/seyahat-rotalari': { label: 'Rutas raras', description: 'Publicaciones de rutas generadas desde viajes en vivo' },
      '/museum': { label: 'Museo' },
      '/collection': { label: 'Coleccion' },
      '/spots': { label: 'Spots' },
      '/for-business': { label: 'Negocios' },
      '/products': { label: 'Productos' },
      '/messages': { label: 'Mensajes' },
    },
  },
  ru: {
    sections: {
      Paylasim: 'Podelitsya',
      Haritalar: 'Karty',
      Kesif: 'Issledovat',
      Ticaret: 'Torgovlya',
      Hesap: 'Akkount',
    },
    quickShare: 'Bystraya publikatsiya',
    quickMaps: 'Bystrye karty',
    pinnedActionLabel: 'Sozdat spot',
    itemByHref: {
      '/create-spot': { label: 'Sozdat spot', description: 'Otkryt zapros i poluchit pomoshch soobshchestva' },
      '/share/rare': { label: 'Ya videl redkoe', description: 'Bystro soobshchit o redkoy nakhodke' },
      '/discovery?compose=1': { label: 'Redkoe puteshestvie', description: 'Delitsya foto i istoriyami s soobshchestvom' },
      '/share/collection': { label: 'Dobavit kollektsiyu', description: 'Opublikovat fizicheskiy predmet kollektsii' },
      '/rare-map': { label: 'Karta redkikh tovarov', description: 'Fizicheskie nakhodki redkikh tovarov' },
      '/rare-travel-map': { label: 'Karta redkikh puteshestviy', description: 'Sotsialnyye publikatsii Discovery' },
      '/rare-travel-plan': { label: 'Plan redkogo puteshestviya', description: 'Umnyy planirovshchik marshrutov' },
      '/': { label: 'Glavnaya' },
      '/sightings': { label: 'Pomoshchi' },
      '/virtual-sightings': { label: 'Virtualnyye pomoshchi' },
      '/discovery': { label: 'Redkoe puteshestvie' },
      '/seyahat-rotalari': { label: 'Redkie marshruty', description: 'Marshrut-publikatsii iz zhivykh puteshestviy' },
      '/museum': { label: 'Muzey' },
      '/collection': { label: 'Kollektsiya' },
      '/spots': { label: 'Spoty' },
      '/for-business': { label: 'Biznes' },
      '/products': { label: 'Produkty' },
      '/messages': { label: 'Soobshcheniya' },
    },
  },
}
